/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelaxRouteImport } from './routes/relax'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'

const RelaxRoute = RelaxRouteImport.update({
  id: '/relax',
  path: '/relax',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/diary': typeof DiaryRoute
  '/learn': typeof LearnRoute
  '/program': typeof ProgramRoute
  '/relax': typeof RelaxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/diary': typeof DiaryRoute
  '/learn': typeof LearnRoute
  '/program': typeof ProgramRoute
  '/relax': typeof RelaxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/diary': typeof DiaryRoute
  '/learn': typeof LearnRoute
  '/program': typeof ProgramRoute
  '/relax': typeof RelaxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/calculator'
    | '/dashboard'
    | '/diary'
    | '/learn'
    | '/program'
    | '/relax'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/calculator'
    | '/dashboard'
    | '/diary'
    | '/learn'
    | '/program'
    | '/relax'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/calculator'
    | '/dashboard'
    | '/diary'
    | '/learn'
    | '/program'
    | '/relax'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  CalculatorRoute: typeof CalculatorRoute
  DashboardRoute: typeof DashboardRoute
  DiaryRoute: typeof DiaryRoute
  LearnRoute: typeof LearnRoute
  ProgramRoute: typeof ProgramRoute
  RelaxRoute: typeof RelaxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relax': {
      id: '/relax'
      path: '/relax'
      fullPath: '/relax'
      preLoaderRoute: typeof RelaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  CalculatorRoute: CalculatorRoute,
  DashboardRoute: DashboardRoute,
  DiaryRoute: DiaryRoute,
  LearnRoute: LearnRoute,
  ProgramRoute: ProgramRoute,
  RelaxRoute: RelaxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
